language: ruby
bundler_args: --without development native_extensions
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - 1.8.7
  - ree
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq libalut-dev
script: RAILS_ENV=test bundle exec rake spec
